### ISSUE TITLE
selector-class-pattern fails on selectors with more than 2 dashes

### ISSUE THREAD

**Issue by emartini** [bjankord/stylelint-config-sass-guidelines#1]
Hi,

I've experienced this issue when I wrote a selector that includes more than 2 dashes

```css
.drop-open-transitionend {
   display: block;
}
```

> Selector should be written in lowercase with hyphens.   selector-class-pattern.

If I wrote it as follows

```css
.drop-open {
   &-transitionend {
      display: block;
   }
}
```

It just works.

Is it the intended behavior ?
