### ISSUE TITLE
Order `dollar-variables` should always come first

### ISSUE THREAD

**Issue by dannobytes** [bjankord/stylelint-config-sass-guidelines#231]
For SCSS users, sometimes we need to assign custom CSS properties to SCSS variables, which requires those variables be defined *before* custom properties are. But with the current ordering, this is impossible.

```scss
div {
  $color: blue;

  // Throws an error saying this should be placed above $color.
  --theme-color: #{$color};
}
```

Can we swap the ordering here of `custom-properties` and `dollar-variables` so that variables always come first and before all others?

e.g.
```js
    "order/order": [
      [
        "dollar-variables",
        "custom-properties",
        ...
```
