### ISSUE TITLE
sass (tabs) style syntax linting not working

### ISSUE THREAD

**Issue by Andrew-Dyachenko** [bjankord/stylelint-config-sass-guidelines#37]
Hi there!

I'm trying to set up SASS _(tabs style)_ linting with _stylelint-config-sass-guidelines_, but it seems like linter do not apply SASS syntax option `syntax: 'sass'` in webpack config file and continue to check styles as SCSS.

I love SASS syntax for its minimalism and purity. How I should set up SASS linting here?

**SASS styles**

![img-2018-09-29-17-35-21](https://user-images.githubusercontent.com/10127643/46247021-2f7b5c00-c40e-11e8-97d0-365ddcf82d88.png)

**Linting result**

![img-2018-09-29-17-26-23](https://user-images.githubusercontent.com/10127643/46247045-7ec18c80-c40e-11e8-9e73-9d97b2a79dba.png)

**Webpack**

![img-2018-09-29-17-29-59](https://user-images.githubusercontent.com/10127643/46247068-c7794580-c40e-11e8-8664-ddf3ec683d62.png)

**.stylelint.yml**
```
---
extends: stylelint-config-sass-guidelines
plugins:
  - stylelint-selector-bem-pattern
rules:
  plugin/selector-bem-pattern:
    preset: suit
    componentName: \w+
    componentSelectors:
      initial: ^\\.{componentName}(?:-[a-z]+)?$
      combined: ^\\.combined-{componentName}-[a-z]+$
    utilitySelectors: ^\\.util-[a-z]+$
  indentation: tab
  string-quotes: single
  no-duplicate-selectors: true
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  selector-combinator-space-after: always
  selector-class-pattern: null
  selector-attribute-quotes: always
  selector-attribute-operator-space-before: never
  selector-attribute-operator-space-after: never
  selector-attribute-brackets-space-inside: never
  declaration-block-trailing-semicolon: always
  declaration-no-important: true
  declaration-colon-space-before: never
  declaration-colon-space-after: always-single-line
  number-leading-zero: never
  function-url-quotes: never
  font-weight-notation: numeric
  font-family-name-quotes: always-where-recommended
  comment-whitespace-inside: always
  comment-empty-line-before: always
  selector-pseudo-element-colon-notation: double
  selector-pseudo-class-parentheses-space-inside: never
  media-feature-range-operator-space-before: always
  media-feature-range-operator-space-after: always
  media-feature-parentheses-space-inside: never
  media-feature-colon-space-before: never
  media-feature-colon-space-after: always
  rule-empty-line-before:
    - never-multi-line
    - except:
      - after-single-line-comment
```
